import { useState } from 'react';
import { LegalLayout, LegalSection } from '../../components/layout/LegalLayout';
import { AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const SECTIONS: LegalSection[] = [
  { id: 'purpose', title: 'Purpose' },
  { id: 'no-financial-advice', title: 'No Financial Advice' },
  { id: 'no-guarantees', title: 'No Guarantees' },
  { id: 'market-risks', title: 'Market Risks' },
  { id: 'ai-limitations', title: 'AI Limitations' },
  { id: 'independent-verification', title: 'Independent Verification' },
  { id: 'third-party-data', title: 'Third Party Data' },
  { id: 'professional-advice', title: 'Professional Advice' },
  { id: 'limitation-of-liability', title: 'Limitation of Liability' },
  { id: 'agreement', title: 'Agreement' },
  { id: 'contact', title: 'Contact' }
];

const FinancialDisclaimer = () => {
  const [acknowledged, setAcknowledged] = useState(false);
  const navigate = useNavigate();

  return (
    <LegalLayout
      title="Financial Disclaimer"
      lastUpdated="August 15, 2026"
      readTime="6 min"
      sections={SECTIONS}
    >
      <div className="bg-[#FF4500] text-white p-8 border-[3px] border-black rounded-2xl shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] mb-12 flex flex-col md:flex-row gap-6 items-center">
        <AlertTriangle className="w-16 h-16 shrink-0" strokeWidth={2.5} />
        <div>
          <h2 className="text-3xl font-black uppercase m-0 border-none text-white">Please Read Carefully</h2>
          <p className="text-lg font-bold mt-2 mb-0">
            Before relying on any AI-generated investment insights, you must understand the risks and limitations of our platform.
          </p>
        </div>
      </div>

      <section id="purpose" className="mb-12">
        <h2>Purpose</h2>
        <p>
          InvestIQ AI is designed solely for educational and research purposes. We build tools that help parse complex data rapidly, but these tools are not a substitute for human judgement.
        </p>
      </section>

      <section id="no-financial-advice" className="mb-12">
        <h2>No Financial Advice</h2>
        <p>
          <strong>InvestIQ AI is not a licensed financial advisor.</strong> Nothing contained on our platform constitutes a solicitation, recommendation, endorsement, or offer by InvestIQ AI or any third-party service provider to buy or sell any securities or other financial instruments.
        </p>
      </section>

      <section id="no-guarantees" className="mb-12">
        <h2>No Guarantees</h2>
        <p>
          AI recommendations are based on available public information, historical data, and mathematical models. These models may be inaccurate, flawed, or simply wrong about future market movements. Past performance is not indicative of future results.
        </p>
      </section>

      <section id="market-risks" className="mb-12">
        <h2>Market Risks</h2>
        <p>
          Investing involves substantial risk, including the possible complete loss of capital. Market structures are complex and influenced by unpredictable macroeconomic factors that AI cannot foresee.
        </p>
      </section>

      <section id="ai-limitations" className="mb-12">
        <h2>AI Limitations</h2>
        <p>
          Generative AI and Large Language Models (LLMs) can produce incomplete, outdated, or hallucinated information. While we restrict our models to strictly analyze provided SEC context, edge cases can cause the AI to misinterpret numbers or sentiment.
        </p>
      </section>

      <section id="independent-verification" className="mb-12">
        <h2>Independent Verification</h2>
        <p>
          Users must verify all financial information independently before making decisions. Do not execute a trade based solely on a "Bullish" or "Bearish" signal generated by InvestIQ AI.
        </p>
      </section>

      <section id="third-party-data" className="mb-12">
        <h2>Third Party Data</h2>
        <p>
          Information is sourced from external APIs, SEC EDGAR, and public news sources. We do not guarantee the timeliness, completeness, or accuracy of this third-party data.
        </p>
      </section>

      <section id="professional-advice" className="mb-12">
        <h2>Professional Advice</h2>
        <p>
          You should consult a certified financial advisor, tax professional, or legal counsel before making any investment decisions.
        </p>
      </section>

      <section id="limitation-of-liability" className="mb-12">
        <h2>Limitation of Liability</h2>
        <p>
          InvestIQ AI, its founders, and affiliates are not responsible for any financial losses or damages resulting from the use of our platform.
        </p>
      </section>

      <section id="agreement" className="mb-12">
        <h2>Agreement</h2>
        <p>
          By creating an account, running a search, or viewing a generated report, you acknowledge these limitations and agree to hold InvestIQ AI harmless.
        </p>
      </section>

      <section id="contact" className="mb-12">
        <h2>Contact</h2>
        <p>
          For legal inquiries regarding this disclaimer: 
          <strong> <a href="mailto:legal@investiq.ai">legal@investiq.ai</a></strong>
        </p>
      </section>

      {/* Acknowledgment Card */}
      <div className="mt-16 bg-white dark:bg-[#1a1a1a] p-8 border-[3px] border-black dark:border-white rounded-2xl shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] dark:shadow-[8px_8px_0px_0px_rgba(255,255,255,1)] text-center">
        <h3 className="text-2xl font-black uppercase tracking-tighter mb-4">Acknowledgment</h3>
        <p className="font-medium text-zinc-600 dark:text-zinc-400 mb-8 max-w-lg mx-auto">
          I have read and understood the Financial Disclaimer. I acknowledge that InvestIQ AI does not provide financial advice and I am solely responsible for my investment decisions.
        </p>
        
        {!acknowledged ? (
          <button 
            onClick={() => setAcknowledged(true)}
            className="inline-flex items-center gap-2 bg-black text-white dark:bg-white dark:text-black font-black uppercase tracking-widest px-8 py-4 border-[3px] border-black dark:border-white rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] dark:shadow-[4px_4px_0px_0px_rgba(255,255,255,1)] hover:-translate-y-1 transition-transform"
          >
            I Understand
          </button>
        ) : (
          <div className="flex flex-col items-center gap-4">
            <div className="inline-flex items-center gap-2 bg-blue-500 text-white font-black uppercase tracking-widest px-8 py-4 border-[3px] border-black rounded-xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
              <CheckCircle2 className="w-6 h-6" /> Acknowledged
            </div>
            <button onClick={() => navigate('/')} className="font-bold underline text-sm uppercase tracking-widest hover:text-zinc-500">
              Return to Dashboard
            </button>
          </div>
        )}
      </div>

    </LegalLayout>
  );
};

export default FinancialDisclaimer;
