import { LegalLayout, LegalSection } from '../../components/layout/LegalLayout';

const SECTIONS: LegalSection[] = [
  { id: 'introduction', title: '1. Introduction' },
  { id: 'acceptance', title: '2. Acceptance of Terms' },
  { id: 'eligibility', title: '3. Eligibility' },
  { id: 'accounts', title: '4. User Accounts' },
  { id: 'acceptable-use', title: '5. Acceptable Use' },
  { id: 'ai-content', title: '6. AI Generated Content' },
  { id: 'disclaimer', title: '7. Investment Disclaimer' },
  { id: 'subscriptions', title: '8. Subscription Plans' },
  { id: 'ip', title: '9. Intellectual Property' },
  { id: 'liability', title: '10. Limitation of Liability' },
  { id: 'termination', title: '11. Termination' },
  { id: 'changes', title: '12. Changes to Terms' },
  { id: 'contact', title: '13. Contact' }
];

const TermsOfService = () => {
  return (
    <LegalLayout
      title="Terms of Service"
      lastUpdated="August 15, 2026"
      readTime="8 min"
      sections={SECTIONS}
    >
      <section id="introduction" className="mb-12">
        <h2>1. Introduction</h2>
        <p>
          Welcome to InvestIQ AI. These Terms of Service ("Terms") govern your use of the InvestIQ AI platform, website, and associated services (collectively, the "Service"). 
          InvestIQ AI provides AI-powered investment research, parsing, and analysis tools for educational and informational purposes only.
        </p>
      </section>

      <section id="acceptance" className="mb-12">
        <h2>2. Acceptance of Terms</h2>
        <p>
          By accessing, registering for, or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, do not use the Service.
        </p>
      </section>

      <section id="eligibility" className="mb-12">
        <h2>3. Eligibility</h2>
        <p>
          You must be at least 18 years old to use the Service. By using the Service, you represent and warrant that you meet all eligibility requirements and possess the legal authority to enter into these Terms.
        </p>
      </section>

      <section id="accounts" className="mb-12">
        <h2>4. User Accounts</h2>
        <p>
          To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities occurring under your account. You agree to provide accurate, current, and complete information during registration.
        </p>
      </section>

      <section id="acceptable-use" className="mb-12">
        <h2>5. Acceptable Use</h2>
        <p>You agree not to engage in any of the following prohibited activities:</p>
        <ul>
          <li>Using the Service for any illegal or unauthorized purpose.</li>
          <li>Reverse engineering, decompiling, or disassembling the Service or its underlying AI models.</li>
          <li>Scraping, crawling, or utilizing automated scripts to extract data from the platform.</li>
          <li>Attempting to bypass rate limits or access controls.</li>
          <li>Submitting malicious code, viruses, or spam.</li>
        </ul>
      </section>

      <section id="ai-content" className="mb-12">
        <h2>6. AI Generated Content</h2>
        <p>
          InvestIQ AI uses large language models and proprietary algorithms to parse complex financial documents and generate summaries, sentiment scores, and quantitative projections.
          <strong> AI-generated reports may contain inaccuracies, hallucinations, or outdated information.</strong> You must independently verify all data before making decisions.
        </p>
      </section>

      <section id="disclaimer" className="mb-12">
        <h2>7. Investment Disclaimer</h2>
        <p>
          <strong>InvestIQ AI is not a licensed financial advisor, broker-dealer, or fiduciary.</strong> 
          The Service is provided for educational and research purposes only. No output generated by the Service constitutes financial, investment, legal, or tax advice. You remain solely responsible for your investment decisions and should consult a certified professional before investing.
        </p>
      </section>

      <section id="subscriptions" className="mb-12">
        <h2>8. Subscription Plans</h2>
        <p>
          We offer Free, Professional, and Enterprise plans.
        </p>
        <ul>
          <li><strong>Billing:</strong> Paid plans are billed on a recurring monthly or annual basis.</li>
          <li><strong>Upgrades & Downgrades:</strong> You may change your plan at any time. Prorated charges or credits will be applied accordingly.</li>
          <li><strong>Cancellations:</strong> You may cancel your subscription at any time. Access will continue until the end of your current billing cycle. Refunds are generally not provided.</li>
        </ul>
      </section>

      <section id="ip" className="mb-12">
        <h2>9. Intellectual Property</h2>
        <p>
          All software, branding, user interfaces, proprietary AI prompts, and platform content belong exclusively to InvestIQ AI and its licensors. You are granted a limited, non-exclusive license to use the Service for its intended purpose.
        </p>
      </section>

      <section id="liability" className="mb-12">
        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, InvestIQ AI shall not be liable for any direct, indirect, incidental, consequential, or special damages, including but not loss of profits, trading losses, or data loss arising from your use of the Service or reliance on AI-generated insights.
        </p>
      </section>

      <section id="termination" className="mb-12">
        <h2>11. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account immediately, without prior notice, if you breach these Terms or engage in fraudulent or illegal activities.
        </p>
      </section>

      <section id="changes" className="mb-12">
        <h2>12. Changes to Terms</h2>
        <p>
          We may update these Terms periodically to reflect changes in our platform or legal requirements. We will notify you of material changes via email or platform notification. Continued use of the Service after changes take effect constitutes acceptance.
        </p>
      </section>

      <section id="contact" className="mb-12">
        <h2>13. Contact</h2>
        <p>
          If you have any questions or concerns regarding these Terms, please reach out to our legal team:
        </p>
        <p>
          <strong>Email:</strong> <a href="mailto:support@investiq.ai">support@investiq.ai</a>
        </p>
      </section>

    </LegalLayout>
  );
};

export default TermsOfService;
